# .pre-commit-config.yaml
# Pre-commit configuration for code quality tools
# Place this file at the root of your repository

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace        # remove trailing whitespace
      - id: end-of-file-fixer         # ensure newline at end of files
      - id: check-yaml                # validate YAML files

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.11
        args:
          - --line-length=79

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
        args:
          - --max-line-length=79

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - -r
          - core/
          - -lll   # recursive scan with verbose level
