# Generated by Django 5.2.1 on 2025-05-12 21:30

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=100)),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("segunda", "Segunda-feira"),
                            ("terca", "Terça-feira"),
                            ("quarta", "Quarta-feira"),
                            ("quinta", "Quinta-feira"),
                            ("sexta", "Sexta-feira"),
                            ("sabado", "Sábado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                (
                    "carga_horaria_semanal",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "horas_a_serem_alocadas",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["dia_semana", "horario_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
                (
                    "areas",
                    models.JSONField(
                        help_text="Lista de áreas/palavras-chave do professor"
                    ),
                ),
                (
                    "carga_horaria_maxima_semanal",
                    models.PositiveIntegerField(
                        help_text="Limite de horas semanais que o professor pode ministrar",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Disponibilidade",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("segunda", "Segunda-feira"),
                            ("terca", "Terça-feira"),
                            ("quarta", "Quarta-feira"),
                            ("quinta", "Quinta-feira"),
                            ("sexta", "Sexta-feira"),
                            ("sabado", "Sábado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidades",
                        to="core.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidade",
                "verbose_name_plural": "Disponibilidades",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("horario_inicio__lt", models.F("horario_fim"))
                        ),
                        name="horario_inicio_menor_fim",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Alocacao",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "horas_alocadas",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                ("status_conflito", models.BooleanField(default=False)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alocacoes",
                        to="core.disciplina",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alocacoes",
                        to="core.professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alocação",
                "verbose_name_plural": "Alocações",
                "ordering": ["disciplina"],
                "indexes": [
                    models.Index(
                        fields=["disciplina", "professor"],
                        name="core_alocac_discipl_0c54ae_idx",
                    )
                ],
                "unique_together": {("disciplina", "professor")},
            },
        ),
    ]
