# Generated by Django 5.2.1 on 2025-05-12 22:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_disciplina_dia_semana"),
    ]

    operations = [
        migrations.CreateModel(
            name="Importacao",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("disciplinas", "Disciplinas"),
                            ("professores", "Professores"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="imports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("done", "Concluído"),
                            ("error", "Erro"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("registros_total", models.IntegerField(default=0)),
                ("registros_sucesso", models.IntegerField(default=0)),
                ("registros_erro", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
