# Generated by Django 5.2.1 on 2025-06-03 22:29

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_importacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("segunda", "Segunda-feira"),
                            ("terca", "Terça-feira"),
                            ("quarta", "Quarta-feira"),
                            ("quinta", "Quinta-feira"),
                            ("sexta", "Sexta-feira"),
                            ("sabado", "Sábado"),
                        ],
                        help_text="Dia da semana em que essa aula acontece",
                        max_length=10,
                    ),
                ),
                (
                    "horario_inicio",
                    models.TimeField(help_text="Horário de início da aula"),
                ),
                (
                    "horario_fim",
                    models.TimeField(help_text="Horário de término da aula"),
                ),
            ],
            options={
                "verbose_name": "Aula Recorrente",
                "verbose_name_plural": "Aulas Recorrentes",
                "ordering": ["dia_semana", "horario_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: '1A', 'Turma B', 'Manhã', etc.",
                        max_length=100,
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(
                        help_text="Data da primeira semana de aulas (YYYY-MM-DD)"
                    ),
                ),
                (
                    "data_fim",
                    models.DateField(
                        help_text="Data da última semana de aulas (YYYY-MM-DD)"
                    ),
                ),
                (
                    "carga_horaria_semanal",
                    models.PositiveIntegerField(
                        help_text="Carga horária semanal efetiva desta turma (soma das aulas recorrentes)",
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["disciplina", "nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="alocacao",
            options={
                "ordering": ["turma"],
                "verbose_name": "Alocação",
                "verbose_name_plural": "Alocações",
            },
        ),
        migrations.AlterModelOptions(
            name="disciplina",
            options={
                "ordering": ["nome"],
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.RemoveIndex(
            model_name="alocacao",
            name="core_alocac_discipl_0c54ae_idx",
        ),
        migrations.RemoveField(
            model_name="disciplina",
            name="dia_semana",
        ),
        migrations.RemoveField(
            model_name="disciplina",
            name="horario_fim",
        ),
        migrations.RemoveField(
            model_name="disciplina",
            name="horario_inicio",
        ),
        migrations.RemoveField(
            model_name="disciplina",
            name="horas_a_serem_alocadas",
        ),
        migrations.AlterField(
            model_name="alocacao",
            name="horas_alocadas",
            field=models.PositiveIntegerField(
                help_text="Carga semanal que este professor dará nesta turma",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="carga_horaria_semanal",
            field=models.PositiveIntegerField(
                help_text="Carga horária semanal total exigida pela disciplina",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="nome",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="turma",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turmas",
                to="core.disciplina",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aulas",
                to="core.turma",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alocacao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="alocacao",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alocacoes",
                to="core.turma",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alocacao",
            unique_together={("turma", "professor")},
        ),
        migrations.AddConstraint(
            model_name="aula",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("horario_inicio__lt", models.F("horario_fim"))
                ),
                name="aula_horario_inicio_menor_fim",
            ),
        ),
        migrations.RemoveField(
            model_name="alocacao",
            name="disciplina",
        ),
    ]
