# Generated by Django 5.2.1 on 2025-06-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_aula_turma_alter_alocacao_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disciplina",
            name="carga_horaria_semanal",
        ),
    ]
