# Generated by Django 5.2.1 on 2025-06-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_disciplina_carga_horaria_semanal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turma",
            name="carga_horaria_semanal",
        ),
        migrations.RemoveField(
            model_name="turma",
            name="data_fim",
        ),
        migrations.RemoveField(
            model_name="turma",
            name="data_inicio",
        ),
        migrations.AddField(
            model_name="turma",
            name="dia_semana",
            field=models.CharField(
                blank=True,
                choices=[
                    ("segunda", "Segunda-feira"),
                    ("terca", "Terça-feira"),
                    ("quarta", "Quarta-feira"),
                    ("quinta", "Quinta-feira"),
                    ("sexta", "Sexta-feira"),
                    ("sabado", "Sábado"),
                ],
                help_text="Dia da semana em que essa turma tem aula semanal",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="horario_fim",
            field=models.TimeField(
                blank=True,
                help_text="Horário de término da aula (HH:MM:SS)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="horario_inicio",
            field=models.TimeField(
                blank=True,
                help_text="Horário de início da aula (HH:MM:SS)",
                null=True,
            ),
        ),
    ]
