# Generated by Django 5.2.1 on 2025-06-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_turma_carga_horaria_semanal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disponibilidade",
            name="professor",
        ),
        migrations.DeleteModel(
            name="Aula",
        ),
        migrations.DeleteModel(
            name="Disponibilidade",
        ),
    ]
