# Generated by Django 5.2.1 on 2025-06-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_disponibilidade_professor_delete_aula_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="local",
            field=models.CharField(
                blank=True,
                help_text="Local (ex.: 'Porto Alegre', 'São Leopoldo')",
                max_length=100,
                null=True,
            ),
        ),
    ]
