# Generated by Django 5.2.1 on 2025-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_turma_local"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="creditos_academicos",
            field=models.CharField(
                blank=True,
                help_text="Créditos Acadêmicos (para relatórios/importações genéricas)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="chapa",
            field=models.CharField(
                blank=True,
                help_text="Matrícula ou chapa do professor (para importação)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="modelo",
            field=models.CharField(
                blank=True,
                help_text="Modelo (presencial, remoto, híbrido etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="numero_alunos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de alunos matriculados (para relatórios)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="orientacoes",
            field=models.TextField(
                blank=True, help_text="Orientações para Secretarias", null=True
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="periodo",
            field=models.CharField(
                blank=True,
                help_text="Período (ex.: '2025.1')",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="turma",
            name="tipo_turma",
            field=models.CharField(
                blank=True,
                help_text="Tipo de turma (teoria, prática, TCC etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("disciplinas", "Disciplinas"),
                    ("professores", "Professores"),
                    ("alocacoes", "Alocações genéricas"),
                ],
                max_length=20,
            ),
        ),
    ]
