# Generated by Django 5.2.1 on 2025-06-10 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0009_disciplina_creditos_academicos_professor_chapa_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="alocacao",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alocacoes",
                to="core.professor",
            ),
        ),
    ]
