name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  dev_checks:
    name: Dev Quality Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --no-cache-dir \
            black isort flake8 flake8-bugbear mypy bandit safety pytest pytest-django coverage pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run formatting and import sorting
        run: |
          black --check .
          isort --check-only --profile black .

      - name: Lint with Flake8
        run: flake8 . --max-line-length=79

      - name: Type checking with mypy
        run: mypy .

      # - name: Security scan with Bandit
      #   run: bandit -r core/ -iii

      - name: Dependency vulnerability check with Safety
        run: safety check --full-report

  test:
    name: Run Tests and Coverage
    runs-on: ubuntu-latest
    needs: dev_checks
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django coverage

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
